### ISSUE TITLE
Powershell gallery not valid error while installing azure module 

### ISSUE THREAD

**Issue by AliJafri117** [cyberark/SkyArk#12]
Hello Guys

      It is my first time here so apologies for any mistakes i make. In our environment, our amazon skyark is working and able to scan and give report. But for some reason, I am having issues installing skyark module on our azure environment. I looked here and online but can not seem to find a solution. I am doing this on a azure server created specifically for azure skyark, and sever has gpo overide. I will post the error I am getting and hopefully one of you guys can help me resolve. Thanks! 

![image](https://user-images.githubusercontent.com/71282722/93116884-eb7dd200-f68b-11ea-91e4-a262d26a679b.png)

**Comment by Hechtov** [comment]
@AliJafri117 did you manage to successfully install the Azure PowerShell Module?
Make sure you open the Powershell cli window with Admin privileges, it may help.
Also, you can install the Azure PowerShell module by using a MSI installer, look at the details here:
https://docs.microsoft.com/en-us/powershell/azure/install-az-ps-msi?view=azps-4.7.0
and here is an installer download link (for version 4.6.1):
https://github.com/Azure/azure-powershell/releases/download/v4.6.1-August2020/Az-Cmdlets-4.6.1.33350-x64.msi
Because it's not a direct issue with SkyArk (but with the prerequisite of installing Azure PowerShell module), I'm going to close this issue. You should have here in the links all you need to solve your problem. If not, you can contact me on Tweeter @Hechtov and I will help more.
Thanks.
