### ISSUE TITLE
Bitdefender detects malware in AWSHostRecon.ps1

### ISSUE THREAD

**Issue by pstutzinger** [cyberark/SkyArk#16]
\SkyArk-master\SkyArk-master\AWSHostRecon\AWSHostRecon.ps1 is infected with Heur.BZC.PZQ.Boxter.692.6D1F6FA8 and was moved to quarantine. It is recommended that you run a System Scan to make sure your system is clean.

**Comment by Hechtov** [comment]
@pstutzinger - did you execute AWSHostRecon.ps1 and the AV flagged it as a suspicious file?
Or already when the AWSHostRecon.ps1 file touched the disk without running it- did it also detected the  as suspicious?

The answer is that this file is clean... there is no harm at all in running it.

First, AWSHostRecon.ps1 isn't finalized (like its readme file explains, it's only an unfinished POC).
Second, the nature of this script is to harvest and search the endpoint for AWS fingerprints and AWS sensitive data. Therefore, I can assume this is the reason for the this specific AV to flag it as a suspicious script. However, this is the declared intention of the AWSHostRecon.ps1, the goal is to demonstrate and show what possible attackers can get from the tested endpoint if it will be compromised. With the results, the security team can take actions and eliminate the discovered sensitive data before real attackers find it.
In addition, of course the script only works locally and doesn't send anything externally from the endpoint, and it's an open source, you can review the script's code and see it by yourself.

**Comment by Hechtov** [comment]
@pstutzinger please see my previous comment.
This alert is a clear False Positive.
The script's code is open source and everyone can review it, you can see that it doesn't harm anything and doesn't include malicious code.
In addition, I scanned today again the AWSHostRecon.ps1 file in VirusTotal and all the 58 integrated Anti Virus didn't detect it as a malicious, because it's indeed a benign file.
I'm going to close this issue for now.
