### ISSUE TITLE
Name resolution failure attempting to reach service in region      | e-west-2

### ISSUE THREAD

**Issue by Iwishiwasfry** [cyberark/SkyArk#9]
Hi

Am trying to run this but get the following response : 

Line |
 635 |      $managedPolicies = Get-IAMPolicyList -OnlyAttached $true
     |                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Name resolution failure attempting to reach service in region
     | e-west-2 (as supplied to the -Region parameter or from
     | configured shell default). Operation timed out Operation timed
     | out. Possible causes:  - The region may be incorrectly
     | specified (did you specify an availability zone?).  - The
     | service may not be available in the region.  - No network
     | connectivity. See
     | https://docs.aws.amazon.com/general/latest/gr/rande.html for
     | the latest service availability across the AWS regions.

From the output not sure if the "u" is being dropped for some reason when entering the region but am entering as follows : 
<img width="470" alt="Screenshot 2020-08-05 at 13 45 43" src="https://user-images.githubusercontent.com/69248093/89414286-0f133b80-d722-11ea-95ef-50276db630c9.png">

Running this on a mac - catalina v10.15.6.
Using PowerShell 7.0.3

**Comment by Hechtov** [comment]
Hi @Iwishiwasfry, Thanks for raising this issue.
You encountered a very weird bug... don't know why the "u" letter got out from the "region" parameter.
Anyway.. I fixed it the last code change.
I changed it entirely, now the scan doesn't ask the user for a "default region" at all. That because it doesn't really matter, the scan only perform queries to the IAM service, and IAM is cross regions.
So the scan sets the default region automatically to "us-east-1".
Please try again the scan!
And feel free to update me if there are other errors.
Thanks
Asaf
